server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /data/loki/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: ben_logs
      __path__: /etc/ben/output/*
  - targets:
      - localhost
    labels:
        job: ben_qc
        __path__: /etc/ben/jobs/ben-qc_*.txt
  - targets:
      - localhost
    labels:
        job: ben_assign
        __path__: /etc/ben/jobs/ben-assign_*.txt
  - targets:
      - localhost
    labels:
        job: ben_ecopcr
        __path__: /etc/ben/jobs/ben-ecopcr_*.txt
  - targets:
      - localhost
    labels:
        job: ben_blast
        __path__: /etc/ben/jobs/ben-blast_*.txt
  - targets:
      - localhost
    labels:
        job: ben_ac
        __path__: /etc/ben/jobs/ben-ac_*.txt
  - targets:
      - localhost
    labels:
        job: ben_newick
        __path__: /etc/ben/jobs/ben-newick_*.txt
  - targets:
      - localhost
    labels:
        job: ben_tronko
        __path__: /etc/ben/jobs/ben-tronko_*.txt