{
 "title": "overview",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "tronko", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ben Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "delta(ben_errors_count{job=\"backup\"}[$__rate_interval])",
     "legendFormat": "Counter"
    }
   ]
  },
  {
   "title": "Ben Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "{job=\"ben_logs\"} |~\"(?i)kill\""
    },
    {
     "expr": "{job=\"ben_logs\"} |~\"(?i)fail\""
    },
    {
     "expr": "{job=\"ben_logs\"} |~\"(?i)error\""
    }
   ]
  },
  {
   "title": "Node Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "crux00_running / crux00_size", "legendFormat": "crux00" },
    { "expr": "crux01_running / crux01_size", "legendFormat": "crux01" },
    { "expr": "crux02_running / crux02_size", "legendFormat": "crux02" },
    { "expr": "crux03_running / crux03_size", "legendFormat": "crux03" },
    { "expr": "crux04_running / crux04_size", "legendFormat": "crux04" },
    { "expr": "crux05_running / crux05_size", "legendFormat": "crux05" },
    { "expr": "crux06_running / crux06_size", "legendFormat": "crux06" }
   ]
  },
  {
   "title": "Ben Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "ben_queued_jobs_total", "legendFormat": "queued" },
    { "expr": "ben_running_jobs_total", "legendFormat": "running" },
    { "expr": "ben_finished_jobs_total", "legendFormat": "finished" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "tronko02"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "tronko03"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "tronko04"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "crux00"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "crux01"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "crux02"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "crux03"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "crux04"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "crux05"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "crux06"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "tronko02"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "tronko03"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "tronko04"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "crux00"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "crux01"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "crux02"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "crux03"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "crux04"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "crux05"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "crux06"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "tronko02"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "tronko03"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "tronko04"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "crux00"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "crux01"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "crux02"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "crux03"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "crux04"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "crux05"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "crux06"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "tronko02"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "tronko03"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "tronko04"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "crux00"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "crux01"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "crux02"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "crux03"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "crux04"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "crux05"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "crux06"
    }
   ]
  },
  {
   "title": "Network Operational Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "tronko02 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "tronko03 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "tronko04 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "crux00 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "crux01 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "crux02 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "crux03 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "crux04 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "crux05 - {{device}}"
    },
    {
     "expr": "node_network_up{instance=\"localhost:9100\",job=\"node_export\"}",
     "legendFormat": "crux06 - {{device}}"
    }
   ]
  },
  {
   "title": "FileSystem Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "tronko02"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "tronko03"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "tronko04"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "crux00"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "crux01"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "crux02"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "crux03"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "crux04"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "crux05"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "crux06"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "tronko02 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "tronko03 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "tronko04 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "crux00 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "crux01 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "crux02 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "crux03 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "crux04 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "crux05 - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "crux06 - {{device}}"
    }
   ]
  },
  {
   "title": "Network Traffic Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "tronko02"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "tronko03"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "tronko04"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "crux00"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "crux01"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "crux02"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "crux03"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "crux04"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "crux05"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"localhost:9100\",job=\"node_export\",device=\"enp1s0\"}[$__rate_interval])",
     "legendFormat": "crux06"
    }
   ]
  }
 ]
}