name: Crux Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: untar crux_db folder
        run: |
          cd test/
          tar xvzf crux_db.tar.gz
          cd crux_db/
          chmod +x crux.sh
          chmod +x docker-crux.sh
      - name: build docker crux image
        run:
          docker build -t crux .
      - name: run docker container 
        run: |
          docker run -d -it --mount "src=$(pwd)/test/crux_db,target=/app/crux_db,type=bind" --name crux crux
          docker inspect crux
      - name: run docker-crux.sh inside crux container
        run: docker exec crux bash "conda run crux /app/crux_db/docker-crux.sh"
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      
      # - name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKER_HUB_USERNAME }}/crux:latest
      #     cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/crux:buildcache
      #     cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/crux:buildcache,mode=max
