{
 "title": "Tronko",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chunk09",
    "label": "chunk09",
    "query": {
     "query": "label_values(node_exporter_build_info{branch=\"debian/sid\"},instance)"
    }
   },
   {
    "name": "chunk08",
    "label": "chunk08",
    "query": {
     "query": "label_values(node_exporter_build_info{branch=\"debian/sid\"},instance)"
    }
   },
   {
    "name": "chunk00",
    "label": "chunk00",
    "query": {
     "query": "label_values(node_exporter_build_info{branch=\"debian/sid\"},instance)"
    }
   },
   {
    "name": "chunk07",
    "label": "chunk07",
    "query": {
     "query": "label_values(node_exporter_build_info{branch=\"debian/sid\"},instance)"
    }
   },
   {
    "name": "chunk06",
    "label": "chunk06",
    "query": {
     "query": "label_values(node_exporter_build_info{branch=\"debian/sid\"},instance)"
    }
   },
   {
    "name": "chunk05",
    "label": "chunk05",
    "query": {
     "query": "label_values(node_exporter_build_info{branch=\"debian/sid\"},instance)"
    }
   },
   {
    "name": "chunk04",
    "label": "chunk04",
    "query": {
     "query": "label_values(node_exporter_build_info{branch=\"debian/sid\"},instance)"
    }
   },
   {
    "name": "chunk03",
    "label": "chunk03",
    "query": {
     "query": "label_values(node_exporter_build_info{branch=\"debian/sid\"},instance)"
    }
   },
   {
    "name": "chunk02",
    "label": "chunk02",
    "query": {
     "query": "label_values(node_exporter_build_info{branch=\"debian/sid\"},instance)"
    }
   },
   {
    "name": "chunk01",
    "label": "chunk01",
    "query": {
     "query": "label_values(node_exporter_build_info{branch=\"debian/sid\"},instance)"
    }
   },
   {
    "name": "benserver",
    "label": "benserver",
    "query": {
     "query": "label_values(node_exporter_build_info{branch=\"debian/sid\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "tronko", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "chunk01"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "chunk02"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "chunk03"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "chunk04"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "chunk05"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "chunk06"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "chunk07"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "chunk08"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "chunk09"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "chunk00"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "chunk01"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "chunk02"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "chunk03"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "chunk04"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "chunk05"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "chunk06"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "chunk07"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "chunk08"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "chunk09"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "chunk00"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "chunk01"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "chunk02"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "chunk03"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "chunk04"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "chunk05"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "chunk06"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "chunk07"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "chunk08"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "chunk09"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "chunk00"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "chunk01"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "chunk02"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "chunk03"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "chunk04"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "chunk05"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "chunk06"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "chunk07"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "chunk08"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "chunk09"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "chunk00"
    }
   ]
  },
  {
   "title": "Ingress Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"enp1s0\"}[5m]) / 1000000",
     "legendFormat": "chunk01"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"enp1s0\"}[5m]) / 1000000",
     "legendFormat": "chunk02"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"enp1s0\"}[5m]) / 1000000",
     "legendFormat": "chunk03"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"enp1s0\"}[5m]) / 1000000",
     "legendFormat": "chunk04"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"enp1s0\"}[5m]) / 1000000",
     "legendFormat": "chunk05"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"enp1s0\"}[5m]) / 1000000",
     "legendFormat": "chunk06"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"enp1s0\"}[5m]) / 1000000",
     "legendFormat": "chunk07"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"enp1s0\"}[5m]) / 1000000",
     "legendFormat": "chunk08"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"enp1s0\"}[5m]) / 1000000",
     "legendFormat": "chunk09"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"enp1s0\"}[5m]) / 1000000",
     "legendFormat": "chunk00"
    }
   ]
  },
  {
   "title": "FileSystem Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "chunk01"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "chunk02"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "chunk03"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "chunk04"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "chunk05"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "chunk06"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "chunk07"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "chunk08"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "chunk09"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "chunk00"
    }
   ]
  },
  {
   "title": "Ben Jobs [%]",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ben_finished_jobs_total ", "legendFormat": "FinishedJobs" },
    { "expr": "ben_running_jobs_total", "legendFormat": "RunningJobs" },
    { "expr": "ben_queued_jobs_total", "legendFormat": "QueuedJobs" }
   ]
  },
  {
   "title": "Node Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((tronko_10_of_10_running / tronko_10_of_10_size))",
     "legendFormat": "chunk00"
    },
    {
     "expr": "avg((tronko_9_of_10_running / tronko_9_of_10_size))",
     "legendFormat": "chunk09"
    },
    {
     "expr": "avg((tronko_8_of_10_running / tronko_8_of_10_size))",
     "legendFormat": "chunk08"
    },
    {
     "expr": "avg((tronko_7_of_10_running / tronko_7_of_10_size))",
     "legendFormat": "chunk07"
    },
    {
     "expr": "avg((tronko_6_of_10_running / tronko_6_of_10_size))",
     "legendFormat": "chunk06"
    },
    {
     "expr": "avg((tronko_5_of_10_running / tronko_5_of_10_size))",
     "legendFormat": "chunk05"
    },
    {
     "expr": "avg((tronko_4_of_10_running / tronko_4_of_10_size))",
     "legendFormat": "chunk04"
    },
    {
     "expr": "avg((tronko_3_of_10_running / tronko_3_of_10_size))",
     "legendFormat": "chunk03"
    },
    {
     "expr": "avg((tronko_2_of_10_running / tronko_2_of_10_size))",
     "legendFormat": "chunk02"
    },
    {
     "expr": "avg((tronko_1_of_10_running / tronko_1_of_10_size))",
     "legendFormat": "chunk01"
    }
   ]
  }
 ]
}